version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand({ping:1})' | mongosh localhost:27017 --quiet || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  mongo-rs-init:
    image: mongo:7.0
    depends_on:
      mongo:
        condition: service_healthy
    entrypoint: >
      bash -lc "
      mongosh --host mongo:27017
      --eval 'rs.initiate({_id:\"rs0\", members:[{_id:0, host:\"mongo:27017\"}]})' || true
      "
    restart: "no"

  mongo-express:
    image: mongo-express:1.0.2-18
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

  api:
    build: ./apps/api
    container_name: api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${API_PORT}:4000"
    depends_on:
      mongo:
        condition: service_healthy

  web:
    build: ./apps/web
    container_name: web
    restart: unless-stopped
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - api

volumes:
  mongo-data: